version: '2.1'
services:
  host1:
    container_name: host1
    ports:
    - 127.0.0.1:8545:8545
    image: parity/parity:v2.7.1-stable
    user: root
    working_dir: /home/parity
    volumes:
    - ./deployment/chain/spec.json:/home/parity/spec.json:ro
    - ./deployment/chain/reserved_peers:/home/parity/reserved_peers:ro
    - ./deployment/1/password:/home/parity/password:ro
    - ./deployment/1/authority.toml:/home/parity/authority.toml:ro
    - ./deployment/1/${NETWORK_NAME}:/home/parity/data/keys/${NETWORK_NAME}
    - ./deployment/dev.json:/home/parity/data/keys/${NETWORK_NAME}/dev.json
    - ./deployment/1/key.priv:/home/parity/data/network/key
    - ./data/1:/home/parity/data
    command: --chain /home/parity/spec.json --config /home/parity/authority.toml -d /home/parity/data 
    networks:
      parity:
        ipv4_address: '10.1.0.101'
  host2:
    container_name: host2 
    image: parity/parity:v2.7.1-stable
    user: root
    working_dir: /home/parity
    volumes:
    - ./deployment/chain/spec.json:/home/parity/spec.json:ro
    - ./deployment/chain/reserved_peers:/home/parity/reserved_peers:ro
    - ./deployment/2/password:/home/parity/password:ro
    - ./deployment/2/authority.toml:/home/parity/authority.toml:ro
    - ./deployment/2/${NETWORK_NAME}:/home/parity/data/keys/${NETWORK_NAME}
    - ./deployment/dev.json:/home/parity/data/keys/${NETWORK_NAME}/dev.json
    - ./deployment/2/key.priv:/home/parity/data/network/key
    - ./data/2:/home/parity/data
    command: --chain /home/parity/spec.json --config /home/parity/authority.toml -d /home/parity/data 
    networks:
      parity:
        ipv4_address: '10.1.0.102'
       
  host3:
    container_name: host3
    image: parity/parity:v2.7.1-stable
    user: root
    working_dir: /home/parity
    volumes:
    - ./deployment/chain/spec.json:/home/parity/spec.json:ro
    - ./deployment/chain/reserved_peers:/home/parity/reserved_peers:ro
    - ./deployment/3/password:/home/parity/password:ro
    - ./deployment/3/authority.toml:/home/parity/authority.toml:ro
    - ./deployment/3/${NETWORK_NAME}:/home/parity/data/keys/${NETWORK_NAME}
    - ./deployment/dev.json:/home/parity/data/keys/${NETWORK_NAME}/dev.json
    - ./deployment/3/key.priv:/home/parity/data/network/key
    - ./data/3:/home/parity/data
    command: --chain /home/parity/spec.json --config /home/parity/authority.toml -d /home/parity/data 
    networks:
      parity:
        ipv4_address: '10.1.0.103'
  monitor:
    image: buythewhale/ethstats_monitor
    volumes:
      - ./monitor/app.json:/home/ethnetintel/eth-net-intelligence-api/app.json
    depends_on:
      - host1
    networks: 
      - parity
  dashboard:
    image: buythewhale/ethstats
    volumes:
      - ./dashboard/ws_secret.json:/eth-netstats/ws_secret.json
    ports:
      - 127.0.0.1:3001:3000
    depends_on:
      - monitor
    networks: 
      - parity
networks:
  parity:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/24
