[parity]
chain = "/home/parity/chain.json"

[account]
password = ["/home/parity/password"]

[network]
reserved_peers = "/home/parity/reserved_peers"

[rpc]
interface = "0.0.0.0"
cors = ["all"]
hosts = ["all"]
apis = ["all"]
server_threads = 8
#processing_threads = 0

[mining]
reseal_on_txs = "none"
engine_signer = "0x59f6566306843fb7d18f782733e19223ca5f07ab"
force_sealing = true
# reseal_max_period = 300000
tx_queue_no_early_reject = true
tx_queue_mem_limit = 0
tx_queue_per_sender = 8192
tx_queue_size = 32768
gas_floor_target = "40000000"

[websockets]
disable = false
port = 8546
interface = "all"
origins = ["http://127.0.0.1:8180"]
apis = ["all"]
hosts = ["all"]

[secretstore]
disable = true

#[misc]
#logging = "secretstore=trace,secretstore_net=trace"
#logging = "engine"
